language: java
jdk: oraclejdk8
before_install:
  - wget https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.14.4-28.1.96/forge-1.14.4-28.1.96-mdk.zip
  - unzip -n forge-1.14.4-28.1.96-mdk.zip
  - rm forge-1.14.4-28.1.96-mdk.zip
install: ./gradlew setupCiWorkspace
script: ./gradlew build
  
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL