modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="GNU General Public License v3.0" #mandatory
issueTrackerURL="https://github.com/Ocelot5836/OpenDeviceMod/issues" #optional

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="Open Device Mod"
updateJSONURL="https://raw.githubusercontent.com/Ocelot5836/storage/master/mods/device-mod/opendevices/update.json"
# displayURL="https://mrcrayfish.com/ TODO add the curse link here
credits="Special thanks to the original mod author MrCrayfish https://mrcrayfish.com/. Thank you to MinecraftDoodler for helping with textures." #optional
authors="Ocelot5836"
description="Adds working electronic devices into Minecraft!"

[[dependencies.opendevices]] #optional
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.opendevices]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.opendevices]]
    modId="filters"
    mandatory=false
    versionRange="[1.1.0,)"
    ordering="AFTER"
    side="CLIENT"
